#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

swift_files() {
    find -L "$1" -type f -name "*.swift" -print0 2>/dev/null \
        | xargs -0 realpath
}

MAC=$(swift_files "$SDIR/../ver-mac/src" | sort -u)
IOS=$(swift_files "$SDIR/../ver-ios/src" | sort -u)

total_lines() {
    local n=0
    while read -r f; do
        [ -n "$f" ] || continue
        n=$(( n + $(wc -l < "$f") ))
    done <<< "$1"
    echo "$n"
}

SHARED=$(comm -12 <(echo "$MAC") <(echo "$IOS"))

N_shared=$(total_lines "$SHARED")
N_IOS=$(total_lines "$IOS")
N_MAC=$(total_lines "$MAC")

printf "ver-ios LOC total / shared / percent: %d / %d / %d%%\n" "$N_IOS" "$N_shared" $(( N_shared * 100 / N_IOS ))
printf "ver-mac LOC total / shared / percent: %d / %d / %d%%\n" "$N_MAC" "$N_shared" $(( N_shared * 100 / N_MAC ))
