#!/bin/bash -e

STEP=$((STEP+1))
echo -e "\n> > > > Step №$STEP. Make an app package for iOS simulator"

rm -rf $APP_IOS

mkdir -p $APP_IOS

cp $SDIR/../ver-ios/.build/arm64-apple-ios-simulator/debug/HelloWorld $APP_IOS/HelloWorld
cp $SDIR/../ver-ios/src/Info.plist $APP_IOS/Info.plist

codesign --force --sign - $APP_IOS >/dev/null 2>&1