#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

BUILD=$SDIR/../.build
mkdir -p $BUILD

cc \
    -I $SDIR/../core/c \
    -o $BUILD/test-c \
    $SDIR/../core/c/DialectContext.c \
    $SDIR/../core/c/DialectController.c \
    $SDIR/../core/c/registerOneliners.c \
    $SDIR/../core/test/c/tests.c \
    $SDIR/../core/test/c/main.c

$BUILD/test-c