#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/../hw"

swift build

APP=.build/HelloWorld.app
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"

cp .build/debug/HelloWorld "$APP/Contents/MacOS/HelloWorld"

cp src/Info.plist "$APP/Contents/Info.plist"

open "$APP"
