#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

BUILD=$SDIR/../.build
mkdir -p $BUILD

swiftc \
    -o $BUILD/test-swift \
    $SDIR/../core/swift/DialectContext.swift \
    $SDIR/../core/swift/DialectController.swift \
    $SDIR/../core/test/swift/tests.swift \
    $SDIR/../core/test/swift/main.swift

$BUILD/test-swift