let cli = CLIComponent()
let kotlin = KotlinComponent()
let llm = LLMComponent()
let swift = SwiftComponent()
let yml = YMLComponent()

otherSetupConsoleLogging(cli.ctrl, "CLI")
//otherSetupConsoleLogging(kotlin.ctrl, "Kotlin")
otherSetupConsoleLogging(llm.ctrl, "LLM")
//otherSetupConsoleLogging(swift.ctrl, "Swift")
//otherSetupConsoleLogging(yml.ctrl, "YML")

cli.setup()
yml.setup()
llm.setup()
kotlin.setup()
swift.setup()
