
let YML_FIELD_DELIMITER = ": "
let YML_PREFIX_FIELD = "        "
let YML_PREFIX_FIELDS = "    fields:"
let YML_PREFIX_OUTPUT = "output:"
let YML_PREFIX_OUTPUT_PATH = "    "
let YML_PREFIX_OUTPUT_TYPE = "        type: "
let YML_PREFIX_SHOULD = "        "
let YML_PREFIX_SHOULDS = "    shoulds:"
let YML_PREFIX_TYPE = "    type: "
let YML_PREFIX_VERSION = "version: "
